name: metwics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"

#t
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{secrets.METRICS_TOKEN}}
          
          plugin_languages: yes
          
          plugin_habits: yes
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{secrets.WAKATIME_TOKEN}}
          plugin_habits_chart_type: chartist
